encoding: utf-8
timezone: UTC
safe: true
kramdown:
  input: GFM

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "master"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "master"
      in_blog: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      in_projects: true
